export declare const container: string;
export declare const isActive: string;
export declare const mainItem: string;
export declare const mainLink: string;
export declare const mainList: string;
export declare const sideItem: string;
export declare const sideLink: string;
export declare const sideList: string;
export declare const sideWrapper: string;
