export { default as Catalog } from './Catalog';
export { default as Footer } from './Footer';
export { default as Header } from './Header';
export { default as Loader } from './Loader';
export { default as MainSlider } from './MainSlider';
export { default as PhoneCard } from './PhoneCard';
export { default as ProductDetails } from './ProductDetails';
export { default as ProductsSlider } from './ProductsSlider';
export { default as ShopByCategory } from './ShopByCategory';
